[tool.pylint]
spelling-dict = "en_US"
ignore = ".venv,actions-runner"

[tool.pylint."messages control"]
disable = [
    "missing-function-docstring",
    "missing-class-docstring",
    "missing-module-docstring",
    "fixme",
]
