[project]
name = "booking-client"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = ["aiohttp", "requests"]

[project.optional-dependencies]
dev = ["black", "isort", "pylint", "mypy"]

[project.scripts]
booking = "booking_client.cli:handle_command"
