[project]
name = "booking-client"
version = "0.1.0"
requires-python = ">=3.7"

dependencies = ["aiohttp >= 3.8.4, <4"]

[project.optional-dependencies]
dev = ["black", "isort", "pylint", "mypy"]

[project.scripts]
booking = "booking_client.cli:entry"
