[project]
name = "booking-common"
version = "0.1.0"
requires-python = ">=3.12" # TODO: Check with vermin

dependencies = []

[project.optional-dependencies]
dev = ["black", "isort", "pylint[spelling]", "mypy"]
