name: Waiting workflow

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  BOOKING_SERVICE_PORT: 8000

jobs:
  book_resource_and_free_it:
    runs-on: [self-hosted]
    steps:
      - id: get_job_id
        run: |
          get_jobs_endpoint="/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs"
          jobs_object=$(gh api \
                          -H "Accept: application/vnd.github+json" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          "$get_jobs_endpoint" \
                        )
          jobs=$(echo "$jobs_object" | jq -r '.jobs[]')
          job=$(echo "$jobs" | jq -r 'select(.name=="${{ github.job }}")')
          job_id=$(echo "$job" | jq -r '.id')
          echo "job_id=$job_id" >> "$GITHUB_OUTPUT"

      - id: book_resource
        run: |
          if [ ${{ github.run_attempt }} = "1" ]
          then
            booking_response=$(
              curl --fail -X 'POST' \
                'http://localhost:8000/booking' \
                -H 'accept: application/json' \
                -H 'Content-Type: application/json' \
                -d '{
                "name": "${{ github.repository }} ${{ github.workflow }} ${{ github.job }}",
                "resource": {
                  "type": "big_machine"
                },
                "github": {
                  "run_id": ${{ github.run_id }},
                  "job_id": ${{ steps.get_job_id.outputs.job_id }},
                  "repo_owner": "${{ github.repository_owner }}",
                  "repo_name": "${{ github.event.repository.name }}"
                }
              }'
            )
            echo "$booking_response"
            booking_id=$(echo "$booking_response" | jq '."info"."id"')
            echo "booking_id=$booking_id"

            tmp_dir="/tmp/actions/${{ github.run_id }}/"
            mkdir -p "$tmp_dir"
            echo "$booking_id" > "$tmp_dir/booking_id"
            exit 1;
          fi

      - run: |
          echo "Accessing resource here"

      - run: |
          booking_id=$(cat /tmp/actions/${{ github.run_id }}/booking_id)
          curl -X 'POST' \
            "http://localhost:8000/booking/$booking_id/finish" \
            -H 'accept: application/json' \
            -d ''
