name: Waiting workflow

on:
  push:
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  work:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Working"
