name: Waiting workflow

on:
  push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  BOOKING_SERVICE_PORT: 8000

jobs:
  book_resource_and_free_it:
    runs-on: [self-hosted]
    steps:
      - id: get_job_id
        run: |
          get_jobs_endpoint="/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs"
          jobs_object=$(gh api \
                          -H "Accept: application/vnd.github+json" \
                          -H "X-GitHub-Api-Version: 2022-11-28" \
                          "$get_jobs_endpoint" \
                        )
          jobs=$(echo "$jobs_object" | jq -r '.jobs[]')
          job=$(echo "$jobs" | jq -r 'select(.name=="${{ github.job }}")')
          job_id=$(echo "$job" | jq -r '.id')
          echo "job_id=$job_id" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.get_job_id.outputs.job_id }}
