name: Waiting workflow

on:
  push:
  workflow_dispatch:

jobs:
  debug:
    runs-on: [self-hosted]
    steps:
      - run: pwd

  wait:
    runs-on: [self-hosted]
    steps:
      - run: exit 1

  work:
    needs: wait
    runs-on: [self-hosted]
    steps:
      - run: echo "Working"
